### ISSUE TITLE
[BUG] Japanese language commas, like 、 instead of ,  are not properly supported when adding terms via add-terms

### ISSUE THREAD

**Issue by Kuratius** [Frosch2010/discord-tabu#2]
Specifically, it will import all forbidden terms as a single long forbidden term, and it will also not correctly recognize duplicates of forbidden terms.

**Comment by jens-muenker** [comment]
Can you send me the tabu-terms.txt so I can work on solving the problem and some correct formatted terms in your language? (Term: forbidden word, ...)

**Comment by Kuratius** [comment]
[tabu-terms.txt](https://github.com/Frosch2010/discord-taboo/files/6269189/tabu-terms.txt)

**Comment by Kuratius** [comment]
This is how the terms get imported. The problem is that the "、" character on a JP keyboard is not parsed correctly when doing imports. I think an easy fix would be to replace all instances of "、" with "," if there are any. Alternatively you could rewrite the code that checks for duplicates and adds linebreaks when the bot sends a player their word to treat "," and "、" the same.

**Comment by jens-muenker** [comment]
The problem should now be solved in the new version 3.0.3 by replacing all "、" with ",".
The "、" can now be used in the tabu-terms.txt and in the Discord chat.
Please write me again if the problem is fixed or persists.
